# Generated by Django 3.1.2 on 2022-05-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyagents',
            options={'ordering': ['-date_registration'], 'verbose_name': 'Полис', 'verbose_name_plural': 'Полисы'},
        ),
        migrations.AddField(
            model_name='policyagents',
            name='agent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='agents.agent', verbose_name='Агент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyagents',
            name='date_end',
            field=models.DateField(default='2022-01-01', verbose_name='Дата окончания действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyagents',
            name='date_start',
            field=models.DateField(default='2022-01-01', verbose_name='Дата начала действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyagents',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=8, verbose_name='Общая премия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyagents',
            name='type_pay',
            field=models.CharField(default='Наличные', max_length=20, verbose_name='Тип оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyagents',
            name='date_registration',
            field=models.DateField(verbose_name='Дата подписания договора'),
        ),
    ]
