# Generated by Django 3.1.2 on 2022-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20220523_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bso',
            options={'ordering': ['date_at'], 'verbose_name': 'БСО', 'verbose_name_plural': 'БСО'},
        ),
        migrations.RemoveField(
            model_name='policyagents',
            name='company',
        ),
        migrations.AddField(
            model_name='policyagents',
            name='type_client',
            field=models.CharField(default=' ', max_length=20, verbose_name='Тип страхователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bso',
            name='date_at',
            field=models.DateField(verbose_name='Дата выдачи агенту'),
        ),
    ]
