# Generated by Django 3.1.2 on 2022-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20220524_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyagents',
            name='status',
            field=models.CharField(default='reconciliation', max_length=20, verbose_name='Статус полиса'),
        ),
    ]
