# Generated by Django 3.1.2 on 2022-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_policyagents_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bso',
            name='date_add',
            field=models.DateField(verbose_name='Дата получения от СК'),
        ),
    ]
