# Generated by Django 3.1.2 on 2022-07-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20220527_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(verbose_name='Дата изменения статуса бланка')),
                ('status', models.CharField(max_length=200, verbose_name='Статус полиса')),
                ('bso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agents.bso', verbose_name='БСО')),
            ],
            options={
                'verbose_name': 'История БСО',
                'verbose_name_plural': 'История БСО',
                'ordering': ['-date_at'],
            },
        ),
    ]
