# Generated by Django 3.1.2 on 2022-07-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_historybso'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Статус БСО')),
                ('name_for_print', models.CharField(max_length=200, verbose_name='Статус для печати')),
            ],
            options={
                'verbose_name': 'Статус БСО',
                'verbose_name_plural': 'Статусы БСО',
            },
        ),
        migrations.AlterField(
            model_name='historybso',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.statusbso', verbose_name='Статус полиса'),
        ),
    ]
