# Generated by Django 3.1.2 on 2022-07-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20220704_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bso',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bso', to='agents.agent', verbose_name='Агент'),
        ),
    ]
