# Generated by Django 3.1.2 on 2022-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20220704_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bso',
            name='date_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи агенту'),
        ),
    ]
