# Generated by Django 3.1.2 on 2022-07-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_auto_20220704_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusbso',
            name='name_for_print',
        ),
    ]
