# Generated by Django 3.1.2 on 2022-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_remove_statusbso_name_for_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='bso',
            name='clear',
            field=models.BooleanField(default=True, verbose_name='Чистый бланк'),
        ),
    ]
