# Generated by Django 3.1.2 on 2022-07-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_bso_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyagents',
            name='bso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.bso', verbose_name='Бланк'),
        ),
        migrations.AlterField(
            model_name='policyagents',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.statusbso', verbose_name='Статус'),
        ),
    ]
