# Generated by Django 3.1.2 on 2022-07-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_auto_20220705_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyagents',
            name='status',
        ),
    ]
