# Generated by Django 3.1.2 on 2022-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_remove_policyagents_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyagents',
            name='bso',
        ),
        migrations.AddField(
            model_name='policyagents',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
