# Generated by Django 3.1.2 on 2022-07-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220704_1202'),
        ('agents', '0016_auto_20220705_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyagents',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.company', verbose_name='СК'),
            preserve_default=False,
        ),
    ]
