# Generated by Django 3.1.2 on 2022-07-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220704_1202'),
        ('agents', '0018_auto_20220705_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historybso',
            options={'verbose_name': 'История БСО', 'verbose_name_plural': 'История БСО'},
        ),
        migrations.AlterField(
            model_name='bso',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='policyagents',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='policyagents',
            name='agent_commission_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='policyagents',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.channel', verbose_name='Канал продаж'),
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала действия')),
                ('agent_com', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='КВ агента')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.channel', verbose_name='Канал продаж')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Компания')),
                ('type_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип полиса')),
            ],
            options={
                'verbose_name': 'КВ агента',
                'verbose_name_plural': 'КВ агента',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='financial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.financial', verbose_name='Финансовая политика'),
        ),
    ]
