# Generated by Django 3.1.2 on 2022-07-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_auto_20220707_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Фин. политика',
                'verbose_name_plural': 'Фин. политика',
            },
        ),
        migrations.AlterModelOptions(
            name='financial',
            options={'verbose_name': 'Элемент фин. политики', 'verbose_name_plural': 'Элементы фин. политики'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='financial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.namefinancial', verbose_name='Финансовая политика'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.namefinancial', verbose_name='Элемент фин. политики'),
        ),
    ]
