# Generated by Django 3.1.2 on 2022-07-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220704_1202'),
        ('agents', '0020_auto_20220707_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='name',
        ),
        migrations.CreateModel(
            name='InputCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала действия')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='КВ агента')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.channel', verbose_name='Канал продаж')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Компания')),
                ('type_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип полиса')),
            ],
            options={
                'verbose_name': 'Входящая комиссия',
                'verbose_name_plural': 'Входящая комиссия',
            },
        ),
    ]
