# Generated by Django 3.1.2 on 2022-07-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_auto_20220707_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.namefinancial', verbose_name='Фин. политика'),
            preserve_default=False,
        ),
    ]
