# Generated by Django 3.1.2 on 2022-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_financial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='date_start',
        ),
        migrations.AddField(
            model_name='namefinancial',
            name='date_start',
            field=models.DateField(default='1990-01-01', verbose_name='Дата начала действия'),
            preserve_default=False,
        ),
    ]
