# Generated by Django 3.1.2 on 2022-03-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0036_auto_20220325_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Статус')),
                ('extended', models.BooleanField(verbose_name='Продлён')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='PolicyOnProlongation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.client', verbose_name='Клиент')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_end', to='main.policy', verbose_name='Полис')),
                ('policy_new', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_new', to='main.policy', verbose_name='Новый полис')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prolongations.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Полис',
                'verbose_name_plural': 'Полисы',
            },
        ),
    ]
