# Generated by Django 3.1.2 on 2022-03-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220325_1459'),
        ('prolongations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyonprolongation',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.policy', verbose_name='Полис'),
        ),
    ]
