# Generated by Django 3.1.2 on 2022-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220418_1211'),
        ('prolongations', '0002_auto_20220325_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название базы')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bso', models.CharField(max_length=50, verbose_name='БСО')),
                ('sp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Страховая премия')),
                ('channel', models.CharField(max_length=50, verbose_name='Канал продаж')),
                ('date_end', models.CharField(max_length=50, verbose_name='Дата окончания')),
                ('manager', models.CharField(max_length=50, verbose_name='Менеджер прошлого года')),
                ('object', models.CharField(max_length=50, verbose_name='Объект страхования')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_base', to='main.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_base', to='main.company', verbose_name='Компания')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_base', to='prolongations.namebase', verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='extended',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='PolicyOnProlongation',
        ),
        migrations.AddField(
            model_name='policybase',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_base', to='prolongations.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='policybase',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_base', to='main.type', verbose_name='Тип полиса'),
        ),
    ]
