# Generated by Django 3.1.2 on 2022-02-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_policy_date_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип полиса')),
            ],
            options={
                'verbose_name': 'Тип полиса',
                'verbose_name_plural': 'Типы полисов',
            },
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.type'),
        ),
    ]
