# Generated by Django 3.1.2 on 2022-02-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220219_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.channel', verbose_name='Канал продаж'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.company', verbose_name='Страховая компания'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип полиса'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
