# Generated by Django 3.1.2 on 2022-02-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220219_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy', to='main.type', verbose_name='Тип полиса'),
        ),
    ]
