# Generated by Django 3.1.2 on 2022-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220219_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Полис', 'verbose_name_plural': 'Полисы'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='sp',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Страховая премия'),
        ),
    ]
