# Generated by Django 3.1.2 on 2022-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220220_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='КВ в %'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sp',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Страховая премия'),
        ),
    ]
