# Generated by Django 3.1.2 on 2022-02-26 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220221_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-date_registration'], 'verbose_name': 'Полис', 'verbose_name_plural': 'Полисы'},
        ),
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.BooleanField(default=False, verbose_name='Агент'),
        ),
        migrations.CreateModel(
            name='Bso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='Серия')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('date_at', models.DateField(auto_now=True, verbose_name='Дата добавления на склад')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bso', to=settings.AUTH_USER_MODEL, verbose_name='БСО')),
            ],
        ),
    ]
