# Generated by Django 3.1.2 on 2022-02-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220226_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bso',
            options={'ordering': ['-date_at'], 'verbose_name': 'БСО', 'verbose_name_plural': 'БСО'},
        ),
        migrations.AlterField(
            model_name='bso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bso', to=settings.AUTH_USER_MODEL, verbose_name='Агент'),
        ),
    ]
