# Generated by Django 3.1.2 on 2022-02-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
