# Generated by Django 3.1.2 on 2022-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220227_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='prolong',
            field=models.BooleanField(default=True, verbose_name='Новый Бизнес'),
        ),
    ]
