# Generated by Django 3.1.2 on 2022-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220228_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bso',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
        migrations.AddField(
            model_name='channel',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
        migrations.AddField(
            model_name='policy',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
        migrations.AddField(
            model_name='user',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
    ]
