# Generated by Django 3.1.2 on 2022-02-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220228_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bso',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='channel',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='client',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='client',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
        migrations.AddField(
            model_name='policy',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='user',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
    ]
