# Generated by Django 3.1.2 on 2022-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220228_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='bso',
            name='status_admin',
            field=models.CharField(default='На складе', max_length=30, verbose_name='Статус админа'),
        ),
        migrations.AddField(
            model_name='bso',
            name='status_agent',
            field=models.CharField(default='В работе', max_length=30, verbose_name='Статус aгента'),
        ),
    ]
