# Generated by Django 3.1.2 on 2022-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220301_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bso',
            name='status_admin',
        ),
        migrations.RemoveField(
            model_name='bso',
            name='status_agent',
        ),
        migrations.AddField(
            model_name='bso',
            name='status',
            field=models.CharField(default='В работе', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bso',
            name='date_at',
            field=models.DateField(auto_now=True, verbose_name='Дата выдачи'),
        ),
    ]
