# Generated by Django 3.1.2 on 2022-03-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220301_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='bso',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bso', to='main.company', verbose_name='Страховая компания'),
        ),
    ]
