# Generated by Django 3.1.2 on 2022-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bso_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='msk',
            field=models.BooleanField(default=False, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='company',
            name='vlgd',
            field=models.BooleanField(default=False, verbose_name='Волгоград'),
        ),
    ]
