# Generated by Django 3.1.2 on 2022-03-09 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220301_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bso',
            options={'ordering': ['status'], 'verbose_name': 'БСО', 'verbose_name_plural': 'БСО'},
        ),
        migrations.CreateModel(
            name='MortgagePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=30, verbose_name='Банк')),
                ('date_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_end', models.DateField(verbose_name='Дата окончания полиса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Ипотечный полис',
                'verbose_name_plural': 'Ипотечный полис',
                'ordering': ['-date_end'],
            },
        ),
    ]
