# Generated by Django 3.1.2 on 2022-03-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220309_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Банк>',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.AlterField(
            model_name='mortgagepolicy',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank', to='main.bank', verbose_name='Банк'),
        ),
    ]
