# Generated by Django 3.1.2 on 2022-03-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220309_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagepolicy',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mortgage_policy', to='main.client', verbose_name='Клиент'),
        ),
    ]
