# Generated by Django 3.1.2 on 2022-03-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220309_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bank', verbose_name='Банк'),
        ),
    ]
