# Generated by Django 3.1.2 on 2022-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_policy_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='bank',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Банк'),
        ),
    ]
