# Generated by Django 3.1.2 on 2022-03-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20220310_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bso',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='bso',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='client',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='company',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='mortgagepolicy',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='mortgagepolicy',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='vlgd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='msk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vlgd',
        ),
    ]
