# Generated by Django 3.1.2 on 2022-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220316_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='prolong',
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(default='newbiz', max_length=30, verbose_name='Статус полиса'),
        ),
    ]
