# Generated by Django 3.1.2 on 2022-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220317_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
    ]
