# Generated by Django 3.1.2 on 2022-03-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_policy_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.type', verbose_name='Тип полиса'),
        ),
    ]
