# Generated by Django 3.1.2 on 2022-03-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20220317_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='bank',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bank', verbose_name='Банк'),
        ),
    ]
