# Generated by Django 3.1.2 on 2022-03-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220317_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.type', verbose_name='Тип полиса'),
        ),
    ]
