# Generated by Django 3.1.2 on 2022-03-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220317_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-date_start'], 'verbose_name': 'Входящее КВ', 'verbose_name_plural': 'Входящее КВ'},
        ),
    ]
