# Generated by Django 3.1.2 on 2022-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_policy_type_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='credit',
            field=models.BooleanField(default=False, verbose_name='Кредитное ТС'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type_pay',
            field=models.BooleanField(default=False, verbose_name='Наличные'),
        ),
    ]
