# Generated by Django 3.1.2 on 2022-05-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220427_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bso',
        ),
    ]
