# Generated by Django 3.1.2 on 2022-05-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_delete_bso'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
