# Generated by Django 3.1.2 on 2022-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_commission_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagepolicy',
            name='type_mortgage',
            field=models.CharField(default='all', max_length=10, verbose_name='Тип ипотечного полиса'),
        ),
    ]
