# Generated by Django 3.1.2 on 2022-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220704_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия полиса'),
        ),
    ]
