# Generated by Django 3.1.2 on 2022-06-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscript', '0002_remove_script_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dscript.script', verbose_name='Скрипт'),
        ),
    ]
