# Generated by Django 3.1.2 on 2022-06-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscript', '0004_auto_20220608_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='dscript.script', verbose_name='Скрипт'),
            preserve_default=False,
        ),
    ]
