# Generated by Django 3.1.2 on 2022-06-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscript', '0005_auto_20220608_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dscript.script', verbose_name='Скрипт'),
        ),
    ]
