# Generated by Django 3.1.2 on 2022-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscript', '0009_auto_20220609_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='neutral',
            field=models.BooleanField(default=False, verbose_name='Позитивный ответ'),
        ),
    ]
