# Generated by Django 3.1.2 on 2022-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscript', '0010_auto_20220609_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='link',
            field=models.BooleanField(default=False, verbose_name='Переход к следующему шагу'),
        ),
    ]
